<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.w3hqxqb' shared service.

return $this->services['service_locator.w3hqxqb'] = new \Symfony\Component\DependencyInjection\ServiceLocator(['serializer' => function () {
    return ${($_ = isset($this->services['jms_serializer']) ? $this->services['jms_serializer'] : $this->getJmsSerializerService()) && false ?: '_'};
}]);
