<?php

namespace AppBundle\Repository;

use AppBundle\Repository\AbstractRepository;

/**
 * PhoneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhoneRepository extends AbstractRepository
{
    public function getPhones($order = 'ASC', $limit = 10, $page)
    {
        $queryBuilder = $this->createQueryBuilder('p')
            ->orderBy('p.id', $order)
        ;

        return $this->paginate($queryBuilder, $limit, $page);
    }
}