<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'fos_rest.exception.controller' shared service.

include_once $this->targetDirs[3].'/vendor/friendsofsymfony/rest-bundle/Controller/ExceptionController.php';
include_once $this->targetDirs[3].'/vendor/friendsofsymfony/rest-bundle/Util/ExceptionValueMap.php';

return $this->services['fos_rest.exception.controller'] = new \FOS\RestBundle\Controller\ExceptionController(${($_ = isset($this->services['FOS\\RestBundle\\View\\ViewHandlerInterface']) ? $this->services['FOS\\RestBundle\\View\\ViewHandlerInterface'] : $this->load('getViewHandlerInterfaceService.php')) && false ?: '_'}, new \FOS\RestBundle\Util\ExceptionValueMap([]), true);
