<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'security.authentication.provider.simple_preauth.secured_area' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/Security/Core/Authentication/Provider/AuthenticationProviderInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/Security/Core/Authentication/Provider/SimpleAuthenticationProvider.php';
include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/Security/Core/User/UserProviderInterface.php';
include_once $this->targetDirs[3].'/src/AppBundle/Provider/FacebookUserProvider.php';
include_once $this->targetDirs[3].'/src/AppBundle/Requester/FacebookRequester.php';
include_once $this->targetDirs[3].'/src/AppBundle/Client/FacebookClient.php';
include_once $this->targetDirs[3].'/src/AppBundle/Manager/UserManager.php';
include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/Security/Core/User/UserCheckerInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/Security/Core/User/UserChecker.php';
include_once $this->targetDirs[3].'/vendor/guzzlehttp/guzzle/src/ClientInterface.php';
include_once $this->targetDirs[3].'/vendor/guzzlehttp/guzzle/src/Client.php';

return $this->services['security.authentication.provider.simple_preauth.secured_area'] = new \Symfony\Component\Security\Core\Authentication\Provider\SimpleAuthenticationProvider(${($_ = isset($this->services['AppBundle\\Authenticator\\FacebookAuthenticator']) ? $this->services['AppBundle\\Authenticator\\FacebookAuthenticator'] : $this->load('getFacebookAuthenticatorService.php')) && false ?: '_'}, new \AppBundle\Provider\FacebookUserProvider(new \AppBundle\Requester\FacebookRequester(new \AppBundle\Client\FacebookClient(${($_ = isset($this->services['csa_guzzle.client.facebook_api']) ? $this->services['csa_guzzle.client.facebook_api'] : ($this->services['csa_guzzle.client.facebook_api'] = new \GuzzleHttp\Client(['base_url' => 'https://graph.facebook.com']))) && false ?: '_'}), ${($_ = isset($this->services['jms_serializer']) ? $this->services['jms_serializer'] : $this->getJmsSerializerService()) && false ?: '_'}, ${($_ = isset($this->services['logger']) ? $this->services['logger'] : $this->getLoggerService()) && false ?: '_'}), new \AppBundle\Manager\UserManager(${($_ = isset($this->services['doctrine.orm.default_entity_manager']) ? $this->services['doctrine.orm.default_entity_manager'] : $this->load('getDoctrine_Orm_DefaultEntityManagerService.php')) && false ?: '_'})), 'secured_area', new \Symfony\Component\Security\Core\User\UserChecker());
