<?php

/**
 * Customer Repository
 */

namespace AppBundle\Repository;

use AppBundle\Repository\AbstractRepository;

/**
 * CustomerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerRepository extends AbstractRepository
{
    /**
     * Get paginate list of Phones
     * @access public
     * @param string $order
     * @param int $limit
     * @param int $page
     * @param int $userId
     * 
     * @return Pagerfanta
     */
    public function getCustomersOfUser($order = 'ASC', $limit = 10, $page = 1, $userId)
    {
        $queryBuilder = $this->createQueryBuilder('c')
            ->where('c.user = :id')
            ->setParameter('id', $userId)
            ->orderBy('c.id', $order)
        ;

        return $this->paginate($queryBuilder, $limit, $page);
    }
}
