<?php

/**
 * Customer Repository
 */

namespace AppBundle\Repository;

use Pagerfanta\Pagerfanta;
use AppBundle\Repository\AbstractRepository;

/**
 * PhoneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhoneRepository extends AbstractRepository
{
    /**
     * Get paginate list of Phones
     * @access public
     * @param string $order
     * @param int $limit
     * @param int $page
     * 
     * @return Pagerfanta
     */
    public function getPhones($order = 'ASC', $limit = 10, $page = 1)
    {
        $queryBuilder = $this->createQueryBuilder('p')
            ->orderBy('p.id', $order)
        ;

        return $this->paginate($queryBuilder, $limit, $page);
    }
}