<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'AppBundle\EventListener\ExceptionListener' shared autowired service.

include_once $this->targetDirs[3].'/src/AppBundle/EventListener/ExceptionListener.php';
include_once $this->targetDirs[3].'/src/AppBundle/Normalizer/NormalizerInterface.php';
include_once $this->targetDirs[3].'/src/AppBundle/Normalizer/AbstractNormalizer.php';
include_once $this->targetDirs[3].'/src/AppBundle/Normalizer/DoctrineExceptionNormalizer.php';

$this->services['AppBundle\\EventListener\\ExceptionListener'] = $instance = new \AppBundle\EventListener\ExceptionListener(${($_ = isset($this->services['jms_serializer']) ? $this->services['jms_serializer'] : $this->getJmsSerializerService()) && false ?: '_'});

$instance->addNormalizer(new \AppBundle\Normalizer\DoctrineExceptionNormalizer([0 => 'Doctrine\\DBAL\\Exception\\ConnectionException', 1 => 'Doctrine\\ORM\\ORMException']));

return $instance;
