<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'hateoas.serializer.exclusion_manager' shared service.

include_once $this->targetDirs[3].'/vendor/willdurand/hateoas/src/Hateoas/Serializer/ExclusionManager.php';

return $this->services['hateoas.serializer.exclusion_manager'] = new \Hateoas\Serializer\ExclusionManager(${($_ = isset($this->services['hateoas.expression.evaluator']) ? $this->services['hateoas.expression.evaluator'] : $this->getHateoas_Expression_EvaluatorService()) && false ?: '_'});
