<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3jvxlmo\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3jvxlmo/appProdProjectContainer.php') {
    touch(__DIR__.'/Container3jvxlmo.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container3jvxlmo\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container3jvxlmo\appProdProjectContainer([
    'container.build_hash' => '3jvxlmo',
    'container.build_id' => '54fd8f43',
    'container.build_time' => 1557145498,
], __DIR__.\DIRECTORY_SEPARATOR.'Container3jvxlmo');
