<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUmolid3\appTestDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUmolid3/appTestDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerUmolid3.legacy');

    return;
}

if (!\class_exists(appTestDebugProjectContainer::class, false)) {
    \class_alias(\ContainerUmolid3\appTestDebugProjectContainer::class, appTestDebugProjectContainer::class, false);
}

return new \ContainerUmolid3\appTestDebugProjectContainer([
    'container.build_hash' => 'Umolid3',
    'container.build_id' => 'e18a5f59',
    'container.build_time' => 1557148442,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUmolid3');
