<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSn6s4u3\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSn6s4u3/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerSn6s4u3.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerSn6s4u3\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerSn6s4u3\appDevDebugProjectContainer([
    'container.build_hash' => 'Sn6s4u3',
    'container.build_id' => '5d02c1c8',
    'container.build_time' => 1557145395,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSn6s4u3');
